local Suites = {}

local DOMAIN_SUITES = {
    require("src.tests.acceptance_host_bootstrap_test"),
    require("src.tests.ip_scope_test"),
    require("src.tests.ipv6_address_test"),
    require("src.tests.gateway_discovery_test"),
    require("src.tests.pcp_test"),
    require("src.tests.nat_pmp_test"),
    require("src.tests.reachability_test"),
    require("src.tests.router_mapping_adapter_test"),
    require("src.tests.upnp_igd_test"),
    require("src.tests.upnp_mapping_adapter_test"),
    require("src.tests.direct_invite_test"),
    require("src.tests.direct_ipv4_listener_test"),
    require("src.tests.direct_ipv4_host_test"),
    require("src.tests.public_ipv4_probe_protocol_test"),
    require("src.tests.public_ipv4_probe_watchdog_test"),
    require("src.tests.direct_opening_code_test"),
    require("src.tests.direct_opening_test"),
    require("src.tests.direct_bridge_test"),
    require("src.tests.transport_ipv6_bridge_test"),
    require("src.tests.direct_connection_test"),
    require("src.tests.direct_gate_test"),
    require("src.tests.direct_transport_test"),
    require("src.tests.direct_session_test"),
    require("src.tests.network_protocol_test"),
    require("src.tests.multiplayer_session_test"),
    require("src.tests.multiplayer_impairment_test"),
    require("src.tests.multiplayer_soak_test"),
    require("src.tests.multiplayer_workshop_boundary_test"),
    require("src.tests.multiplayer_workshop_reliable_test"),
    require("src.tests.multiplayer_capabilities_test"),
    require("src.tests.vendor_authority_test"),
    require("src.tests.truck_authority_test"),
    require("src.tests.truck_session_test"),
    require("src.tests.cutter_maintenance_authority_test"),
    require("src.tests.cutter_maintenance_session_test"),
    require("src.tests.cutter_presentation_test"),
    require("src.tests.cutter_production_session_test"),
    require("src.tests.shared_gui_test"),
    require("src.tests.office_phone_session_test"),
    require("src.tests.guest_job_journey_test"),
    require("src.tests.wrapper_maintenance_authority_test"),
    require("src.tests.wrapper_maintenance_session_test"),
    require("src.tests.machine_relocation_authority_test"),
    require("src.tests.machine_relocation_session_test"),
    require("src.tests.workshop_authority_test"),
    require("src.tests.multiplayer_hud_test"),
    require("src.tests.lan_discovery_test"),
    require("src.tests.lan_reconnect_test"),
    require("src.tests.lan_reconnect_session_test"),
    require("src.tests.lan_screen_test"),
    require("src.tests.direct_screen_test"),
    require("src.tests.direct_composite_transport_test"),
    require("src.tests.direct_composite_session_integration_test"),
    require("src.tests.transport_enet_test"),
    require("src.tests.interaction_test"),
    require("src.tests.player_controller_test"),
    require("src.tests.customer_motion_test"),
    require("src.tests.asset_pack_test"),
    require("src.tests.work_phone_test"),
    require("src.tests.options_test"),
    require("src.tests.sound_test"),
    require("src.tests.pallet_state_test"),
    require("src.tests.warehouse_upgrades_test"),
    require("src.tests.warehouse_layout_test"),
    require("src.tests.warehouse_scene_test"),
    require("src.tests.warehouse_live_acceptance_test"),
    require("src.tests.construction_service_test"),
    require("src.tests.warehouse_construction_test"),
    require("src.tests.mechanic_work_presentation_test"),
    require("src.tests.warehouse_construction_presentation_test"),
    require("src.tests.warehouse_gameplay_test"),
    require("src.tests.warehouse_office_test"),
    require("src.tests.warehouse_authority_test"),
    require("src.tests.warehouse_controls_test"),
    require("src.tests.warehouse_app_entry_test"),
    require("src.tests.pallet_storage_test"),
    require("src.tests.storage_consumption_test"),
    require("src.tests.pallet_rack_screen_test"),
    require("src.tests.forklift_test"),
    require("src.tests.forklift_cargo_test"),
    require("src.tests.forklift_presentation_test"),
    require("src.tests.forklift_lift_lab_test"),
    require("src.tests.warehouse_save_test"),
    require("src.tests.save_contract_test"),
    require("src.tests.input_status_test"),
    require("src.tests.machine_fleet_test"),
    require("src.tests.press_economics_test"),
    require("src.tests.windmill_integration_test"),
}

function Suites.runDomain(context, check)
    for _, suite in ipairs(DOMAIN_SUITES) do suite.run(context, check) end
end

function Suites.verifyAuditCoverage(passed, check)
    require("src.tests.audit_coverage").run(passed, check)
end

return Suites
