"""Pack reviewed seated art with fixed cushion contacts; retain original sources."""
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageDraw
from build_worker_action_assets import lua

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/source/client-seating-v1'
REVIEW = ROOT / 'output/client-seating-v1'
# Reviewed posterior cushion contact in each original 887 px cell.
HIPS = {
    'business-dragon': [(578, 598), (466, 598)],
    'business-fox': [(565, 625), (454, 625)],
    'business-cat': [(591, 643), (591, 643)],
}

def build():
    art = {'anchors': {}, 'metrics': {}}
    records = []
    manifest_path = SOURCE / 'source-manifest.json'
    pinned = {r['character']: r for r in json.loads(manifest_path.read_text())} if manifest_path.exists() else {}
    contact = Image.new('RGBA', (512, 3 * 280), (35, 40, 46, 255))
    draw = ImageDraw.Draw(contact)
    for row, (character, hips) in enumerate(HIPS.items()):
        path = SOURCE / (character + '.png')
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if character in pinned and pinned[character]['sha256'] != digest:
            raise ValueError('Source differs from reviewed manifest: ' + character)
        atlas = Image.open(path).convert('RGBA')
        cells = [atlas.crop((i * atlas.width // 2, 0, (i + 1) * atlas.width // 2, atlas.height)) for i in range(2)]
        boxes = []
        for cell in cells:
            # Remove only near-transparent export haze, retaining all opaque
            # light shirts, cuffs, eye whites and every tail/body pixel.
            cell.putalpha(cell.getchannel('A').point(lambda a: a if a >= 24 else 0))
            boxes.append(cell.getchannel('A').getbbox())
        ratio = 192 / max(b[3] - b[1] for b in boxes)
        out = Image.new('RGBA', (512, 256))
        anchors, metrics = [], []
        for i, (cell, box, hip) in enumerate(zip(cells, boxes, hips)):
            cropped = cell.crop(box)
            resized = cropped.resize((round(cropped.width * ratio), round(cropped.height * ratio)), Image.Resampling.LANCZOS)
            local_hip = ((hip[0] - box[0]) * ratio, (hip[1] - box[1]) * ratio)
            offset = (round(148 - local_hip[0]), round(179 - local_hip[1]))
            frame = Image.new('RGBA', (256, 256))
            frame.alpha_composite(resized, offset)
            bounds = frame.getchannel('A').point(lambda a: 255 if a >= 24 else 0).getbbox()
            if min(bounds) < 3 or max(bounds) > 253:
                raise ValueError('Insufficient frame margin: ' + character)
            out.alpha_composite(frame, (i * 256, 0))
            anchors.append({'x': 148, 'y': 179})
            metrics.append(list(bounds))
            contact.alpha_composite(frame, (i * 256, row * 280 + 24))
            draw.line((i*256+140,row*280+203,i*256+156,row*280+203), fill=(80,240,200))
        draw.text((8, row * 280 + 5), character + ' / neutral, blink / green = cushion', fill='white')
        target = ROOT / 'assets/generated/client-seating-v1' / character / 'sit.png'
        target.parent.mkdir(parents=True, exist_ok=True)
        out.save(target)
        art['anchors'][character] = {'sit': anchors}
        art['metrics'][character] = {'sit': metrics}
        spec_path = ROOT / 'character-motion' / (character + '.json')
        spec = json.loads(spec_path.read_text())
        spec['animations']['sit'] = {
            'path': target.relative_to(ROOT).as_posix(), 'frame_width': 256, 'frame_height': 256,
            'frame_count': 2, 'loop': True, 'role': 'seated_idle', 'fps': .65,
            'pose_order': ['relaxed_eyes_open', 'brief_blink'], 'anchor': {'x': 148, 'y': 179},
            'registration': 'posterior cushion contact', 'body_height_ratio': .703125,
        }
        spec_path.write_text(json.dumps(spec, indent=2) + '\n')
        records.append({'character': character, 'source': path.relative_to(ROOT).as_posix(),
                        'sha256': digest, 'source_hips': hips, 'scale': ratio,
                        'output': target.relative_to(ROOT).as_posix(), 'transparent_haze_threshold': 24})
    (ROOT / 'src/client_seating_art.lua').write_text('-- Generated by tools/build_client_seating_v1.py\nreturn ' + lua(art) + '\n')
    manifest_path.write_text(json.dumps(records, indent=2) + '\n')
    contact.save(REVIEW / 'registered-poses.png')

if __name__ == '__main__':
    build()
