"""Build the cat employee's reviewed 256px runtime strips and static metadata.

Radio Cat's original eight-view strips are copied intact as immutable source
masters. Generated action sheets are split and registered; no poses are drawn
or mirrored here. Run from the repository with the bundled Python runtime.
"""
from pathlib import Path
import json
import hashlib
import sys
from PIL import Image
from build_visitor_character_assets import pack, bounds, body_axis
import build_visitor_character_assets as visitor

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/source/cat-worker-v1"
RUNTIME = ROOT / "assets/generated/characters/cat-worker"
REVIEW = ROOT / "output/cat-worker-review"
DIRECTIONS = ["east", "northeast", "north", "northwest", "west", "southwest", "south", "southeast"]


def build():
    visitor.HEIGHT, visitor.BASELINE = 385, 458
    RUNTIME.mkdir(parents=True, exist_ok=True)
    REVIEW.mkdir(parents=True, exist_ok=True)
    manifest = json.loads((SOURCE / "source-manifest.json").read_text())
    strips = {}
    for record in manifest["sources"]:
        source_path=ROOT / record["source"]
        if hashlib.sha256(source_path.read_bytes()).hexdigest()!=record["sha256"]:
            raise ValueError(f"Source master differs from the approved manifest: {record['source']}")
        im = Image.open(source_path).convert("RGBA")
        if record["kind"] == "locomotion":
            strips[record["action"]] = im.resize((im.width // 2, 256), Image.Resampling.LANCZOS)
        else:
            cols, rows = record["columns"], record["rows"]
            for col, view in enumerate(record["directions"]):
                left, right = round(col * im.width / cols), round((col + 1) * im.width / cols)
                if record["action"] == "rest":
                    # Source layout has slightly uneven row gutters. Split on
                    # actual transparent bands so the next pose's ear tips are
                    # never copied into the current pose or clipped away.
                    import numpy as np
                    alpha = np.asarray(im.getchannel("A"))[:, left:right]
                    occupied = (alpha >= 16).sum(axis=1) >= 6
                    bands, start = [], None
                    for y, filled in enumerate(occupied):
                        if filled and start is None: start = y
                        if start is not None and (not filled or y == len(occupied)-1):
                            end = y if not filled else y+1
                            if end-start >= 40: bands.append((start,end))
                            start=None
                    if len(bands) != rows: raise ValueError(f"Expected {rows} clean rest poses, found {bands}")
                    frames = [im.crop((left,top,right,bottom)) for top,bottom in bands]
                else:
                    frames = [im.crop((left, round(row * im.height / rows), right, round((row + 1) * im.height / rows)))
                              for row in range(rows)]
                normalized = pack(frames).resize((256 * rows, 256), Image.Resampling.LANCZOS)
                strips[f'{record["action"]}_{view}'] = normalized
    anchors, metrics, specs, report = {}, {}, {}, {}
    for action, im in strips.items():
        path = RUNTIME / f"{action}.png"
        im.save(path, optimize=True)
        count = im.width // 256
        a, m = [], []
        for i in range(count):
            frame = im.crop((i * 256, 0, (i + 1) * 256, 256))
            box = bounds(frame)
            a.append({"x": round(body_axis(frame, box), 2), "y": box[3]})
            m.append(list(box))
        anchors[action], metrics[action] = a, m
        role = "gait" if action.startswith("walk") else "directional_idle" if action.startswith("idle") else "action"
        specs[action] = {"path": path.relative_to(ROOT).as_posix(), "frame_width": 256,
                         "frame_height": 256, "frame_count": count, "loop": role != "action",
                         "role": role, "fps": .65 if role == "directional_idle" else 72 / 13 if role == "gait" else 4}
        report[action] = {"frames": count, "sha256": hashlib.sha256(path.read_bytes()).hexdigest()}
    def lua(value):
        if isinstance(value, dict):
            return "{ " + ", ".join(f'["{k}"] = {lua(v)}' for k, v in value.items()) + " }"
        if isinstance(value, list):
            return "{ " + ", ".join(lua(v) for v in value) + " }"
        return str(value)
    for filename, data in (("cat_worker_anchors.lua", anchors), ("cat_worker_metrics.lua", metrics)):
        (ROOT / "src" / filename).write_text('-- Generated by tools/build_cat_worker_assets.py.\nreturn { ["cat-worker"] = ' + lua(data) + ' }\n')
    spec = json.loads((ROOT / "character-motion/cat-worker.json").read_text())
    spec["status"] = "implemented"
    spec["animations"] = {(k+"_east" if k in ("idle","walk") else k): v for k,v in specs.items()}
    spec["directions"]["east"]["walk_animation"]="walk_east"
    spec["directions"]["east"]["idle_animation"]="idle_east"
    spec["runtime_contract"]["registered"] = True
    spec["runtime_contract"]["requires_variable_frame_size_loader"] = False
    spec["implemented_roles"] = ["applicant", "cutter_operator"]
    spec["deferred_roles"] = ["press_operator", "wrapper_operator", "pallet_transport"]
    (ROOT / "character-motion/cat-worker.json").write_text(json.dumps(spec, indent=2) + "\n")
    locomotion = dict(spec)
    locomotion["animations"] = {k: v for k, v in spec["animations"].items() if v["role"] != "action"}
    (REVIEW / "locomotion-spec.json").write_text(json.dumps(locomotion, indent=2) + "\n")
    action_review = dict(spec)
    action_review["audit"] = dict(spec["audit"], center_tolerance=24)
    action_review["audit_note"] = "Arm reaches, tickets, sitting and rising change silhouette centers (20.5px maximum); foot/body anchors stay registered. Action review allows 24px silhouette movement. Locomotion is audited separately at the strict 10px center tolerance."
    (REVIEW / "action-review-spec.json").write_text(json.dumps(action_review, indent=2) + "\n")
    (REVIEW / "build-report.json").write_text(json.dumps(report, indent=2) + "\n")
    # A contact sheet at close to the game's actual visible body height.
    contact = Image.new("RGBA", (8 * 120, 4 * 130), (42, 47, 45, 255))
    for col, view in enumerate(DIRECTIONS):
        for row, prefix in enumerate(("idle", "walk", "operate", "rest")):
            action = prefix if view == "east" and prefix in ("idle", "walk") else f"{prefix}_{view}"
            if action not in strips: continue
            frame = strips[action].crop((0, 0, 256, 256)).resize((110, 110), Image.Resampling.NEAREST)
            contact.alpha_composite(frame, (col * 120 + 5, row * 130 + 15))
    contact.save(REVIEW / "contact.png")
    print(f'Built {len(strips)} cat-worker strips at {RUNTIME}')


if __name__ == "__main__":
    if "--prepare" in sys.argv:
        sources = []
        for path in sorted((SOURCE / "locomotion").glob("*.png")):
            sources.append({"kind": "locomotion", "action": path.stem,
                            "source": path.relative_to(ROOT).as_posix(),
                            "origin": "Mouse Frontier 8.10 reviewed Radio Cat runtime",
                            "sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
        (SOURCE / "source-manifest.json").write_text(json.dumps({"version": 1,
            "generator": "Built-in imagegen for action art; approved Radio Cat locomotion reused intact",
            "sources": sources}, indent=2) + "\n")
        for name, views in (("northern", DIRECTIONS[:4]), ("southern", DIRECTIONS[4:])):
            guide = Image.new("RGBA", (512 * 4, 512))
            for col, view in enumerate(views):
                filename = "idle.png" if view == "east" else f"idle_{view}.png"
                frame = Image.open(SOURCE / "locomotion" / filename).convert("RGBA").crop((0, 0, 512, 512))
                guide.alpha_composite(frame, (col * 512, 0))
            guide.save(SOURCE / f"{name}-direction-guide.png")
    elif "--register-actions" in sys.argv:
        manifest = json.loads((SOURCE / "source-manifest.json").read_text())
        for filename, action, views, prompts in (
            ("operate-northern-v2.png", "operate", DIRECTIONS[:4], ["operate-northern-prompt.txt", "operate-northern-v2-prompt.txt"]),
            ("operate-southern-v1.png", "operate", DIRECTIONS[4:], ["operate-southern-prompt.txt"]),
            ("rest-v2.png", "rest", ["east", "west"], ["rest-prompt.txt", "rest-cleanup-prompt.txt"]),
        ):
            path = SOURCE / filename
            manifest["sources"].append({"kind": "action", "source": path.relative_to(ROOT).as_posix(),
                "action": action, "columns": len(views), "rows": 4, "directions": views,
                "generator": "built-in imagegen", "prompts": [f"assets/source/cat-worker-v1/{p}" for p in prompts],
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest()})
        manifest["rejected_sources"] = [
            {"source": "assets/source/cat-worker-v1/operate-northern-v1.png", "reason": "incorrect east/northeast orientation"},
            {"source": "assets/source/cat-worker-v1/rest-v1.png", "reason": "ambient background glow; replaced by transparency edit"}]
        (SOURCE / "source-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    else:
        build()
