-- Components share one private context and preserve the public App API.
local Runtime = {}
require("src.runtime.context").install(Runtime)
require("src.runtime.player_preferences").install(Runtime)
require("src.runtime.camera").install(Runtime)
require("src.runtime.game_state").install(Runtime)
require("src.runtime.workshop_views").install(Runtime)
require("src.runtime.windmill_commands").install(Runtime)
require("src.runtime.machine_resources").install(Runtime)
require("src.runtime.workshop_authority").install(Runtime)
require("src.runtime.workshop_leases").install(Runtime)
require("src.runtime.lan_startup").install(Runtime)
require("src.runtime.direct_setup").install(Runtime)
require("src.runtime.manual_hosting").install(Runtime)
require("src.runtime.direct_join").install(Runtime)
require("src.runtime.options").install(Runtime)
require("src.runtime.warehouse").install(Runtime)
require("src.runtime.pallet_controls").install(Runtime)
require("src.runtime.input_context").install(Runtime)
require("src.runtime.pointer_dispatch").install(Runtime)
require("src.runtime.keyboard_mobile").install(Runtime)
require("src.runtime.smoke_context").install(Runtime)
require("src.runtime.load").install(Runtime)
require("src.runtime.lan_reconnect").install(Runtime)
require("src.runtime.multiplayer_events").install(Runtime)
require("src.runtime.multiplayer_update").install(Runtime)
require("src.runtime.direct_hosts").install(Runtime)
require("src.runtime.direct_connection").install(Runtime)
require("src.runtime.simulation").install(Runtime)
require("src.runtime.render").install(Runtime)
require("src.runtime.input_callbacks").install(Runtime)
require("src.runtime.lifecycle").install(Runtime)

return Runtime.App
