local Config = {
    baseWidth = 960,
    baseHeight = 678,
    player = {
        spawnX = 500,
        spawnY = 455,
        speed = 155,
        drawScale = 0.30,
    },
    customer = {
        character = "business-dragon",
        characterPool = { "business-dragon", "business-fox", "business-cat" },
        drawScale = 0.34,
        speed = 72,
        walkAnimationRate = 4,
        arrivalDelay = 1.25,
        maxWaitSeconds = 300,
        interactionRadius = 58,
        -- Main glass entrance to the client lounge.
        -- Every segment is kept inside the warehouse walk mask.
        route = {
            { x = 645, y = 235 },
            { x = 650, y = 245 },
            { x = 640, y = 270 },
            { x = 630, y = 295 },
            { x = 635, y = 320 },
            { x = 650, y = 340 },
            { x = 680, y = 350 },
            { x = 720, y = 355 },
            { x = 760, y = 360 },
        },
        seatSpots = {
            { name = "left-chair", x = 725, y = 320, facing = 1 },
            { name = "couch", x = 812, y = 320, facing = -1 },
            { name = "right-chair", x = 894, y = 390, facing = -1 },
        },
    },
    vendor = {
        character = "tan-cat", drawScale = 0.34, speed = 68, walkAnimationRate = 4, arrivalDelay = 4.5, interactionRadius = 58,
        route = {
            { x = 645, y = 235 }, { x = 650, y = 245 }, { x = 640, y = 270 },
            { x = 630, y = 295 }, { x = 635, y = 320 }, { x = 650, y = 340 },
            { x = 680, y = 350 }, { x = 710, y = 340 },
        },
    },
    loadingBay = {
        sourceX = 200,
        sourceY = 170,
        frameWidth = 260,
        frameHeight = 260,
        frameCount = 5,
        duration = 0.9,
        interaction = { x = 300, y = 285, radius = 62 },
        obstacle = { x = 215, y = 267, radius = 55 },
    },
    truck = {
        frameSize = 512,
        cargoFrameCount = 5,
        scheduleDelay = 1.25,
        backingDuration = 2.2,
        cargoDuration = 0.75,
        -- The truck keeps one physical size and translates backward into the bay.
        start = { x = -150, y = 420, scale = 0.94 },
        -- The truck sprite's rear opening sits to the right of its image origin.
        -- This anchor places that opening on the loading-bay aperture center.
        -- At the parked scale the rear cargo opening fills the dock aperture
        -- (the truck body extends out onto the loading apron).
        parked = { x = 54, y = 318, scale = 0.94 },
        rearOpeningOffsetX = 160,
        interaction = { x = 218, y = 310, radius = 58 },
        obstacle = { offsetX = 0, offsetY = -8, radius = 72 },
        aperture = {
            { x = 138, y = 149 },
            { x = 270, y = 124 },
            { x = 270, y = 247 },
            { x = 138, y = 273 },
        },
    },
    cutterGui = {
        buttonFrameSize = 128,
        buttonFrameCount = 4,
        motionFrameWidth = 768,
        motionFrameHeight = 512,
        motionFrameCount = 5,
    },
    cutterPlacement = {
        spawnX = 625,
        spawnY = 405,
        defaultDirection = "northwest",
        speed = 52,
        interactionRadius = 88,
        obstacleRadius = 68,
        collisionHalfWidth = 61,
        collisionHalfHeight = 19,
        operatorDistanceX = 82,
        operatorDistanceY = 48,
        drawScale = 0.34,
        frameSize = 512,
        frameCount = 4,
    },
    wrapperPlacement = {
        -- Factory-floor spawn, clear of the reception wall and lobby furniture.
        spawnX = 740,
        spawnY = 430,
        defaultDirection = "northwest",
        speed = 58,
        interactionRadius = 96,
        obstacleRadius = 44,
        collisionHalfWidth = 46,
        collisionHalfHeight = 17,
        operatorDistanceX = 54,
        operatorDistanceY = 34,
        palletRadius = 108,
        drawScale = 0.22,
        frameSize = 512,
        frameCount = 4,
    },
    palletLogistics = {
        -- The loose-pallet art fills its frame while the pallet inside the
        -- loaded-jack composite occupies half a frame. This 0.5 ratio makes
        -- their visible world footprints match.
        drawScale = 0.26,
        obstacleRadius = 26,
        collisionHalfWidth = 33,
        collisionHalfHeight = 11,
        unloadDuration = 0.65,
        unloadOrigin = { x = 218, y = 304 },
        spawnPoints = {
            { x = 338, y = 344 },
            { x = 410, y = 374 },
            { x = 482, y = 404 },
            { x = 360, y = 450 },
            { x = 442, y = 480 },
        },
    },
    palletJack = {
        spawnX = 560,
        spawnY = 520,
        speed = 112,
        loadedSpeed = 82,
        interactionRadius = 58,
        pickupRadius = 68,
        obstacleRadius = 26,
        loadedObstacleRadius = 40,
        collisionHalfWidth = 34,
        collisionHalfHeight = 10,
        loadedCollisionHalfWidth = 44,
        loadedCollisionHalfHeight = 14,
        drawScale = 0.52,
        carriedPalletArtRatio = 0.5,
        operatorDistanceX = 42,
        operatorDistanceY = 24,
        frameSize = 256,
        frameCount = 4,
    },
    interactables = {
        computer = { x = 500, y = 185, radius = 62 },
        cutter = { x = 625, y = 405, radius = 78 },
    },
    paths = {
        warehouse = "assets/generated/warehouse-layout-final.png",
        walkmask = "assets/generated/warehouse-layout-final-walkmask.png",
        polar = "assets/generated/polar-115-sprite-sheet-clear-table-transparent.png",
        polarDirections = "assets/generated/polar-cutter-directions-strip.png",
        rabbit = "assets/generated/rabbit-worker-atlas.png",
        emptyPallet = "assets/generated/empty-pallet.png",
        paperStack = "assets/generated/paper-stack.png",
        toolboxSmall = "assets/generated/toolbox-small.png",
        toolboxLarge = "assets/generated/toolbox-large.png",
        paperBoxes = "assets/generated/paper-storage-boxes-strip.png",
        loadingBayDoor = "assets/generated/loading-bay-door-strip.png",
        deliveryTruck = "assets/generated/delivery-truck-open.png",
        truckCargoDoor = "assets/generated/truck-cargo-door-strip.png",
        polarOperatorConsole = "assets/generated/polar-operator-console.png",
        cutterControlButtons = "assets/generated/cutter-control-buttons-strip.png",
        cutterClamp = "assets/generated/cutter-clamp-strip.png",
        cutterBlade = "assets/generated/cutter-blade-strip.png",
        picturePress = "assets/generated/picture-press-transparent.png",
        skidWrapperDirections = "assets/generated/skid-wrapper-directions-strip.png",
        wrappedPalletStages = "assets/generated/wrapped-pallet-stages-strip.png",
        loadedPaperPallet = "assets/generated/loaded-paper-pallet.png",
        loadedPaperPalletDirections = "assets/generated/loaded-paper-pallet-directions-strip.png",
        palletJack = "assets/generated/pallet-jack-directions-strip.png",
        palletJackLoaded = "assets/generated/pallet-jack-loaded-directions-strip.png",
        vendorProductPallets = "assets/generated/vendor-product-pallets-atlas.png",
        boxedPaperPalletStages = "assets/generated/boxed-paper-pallet-stages-atlas.png",
        polarBackButton = "assets/generated/polar-back-button-states-strip.png",
    },
    characters = {
        ["tan-cat"] = { idle = "assets/generated/characters/tan-cat/idle.png", walk = "assets/generated/characters/tan-cat/walk.png", sit = "assets/generated/characters/tan-cat/sit.png" },
        ["green-blazer-cat"] = { idle = "assets/generated/characters/green-blazer-cat/idle.png", walk = "assets/generated/characters/green-blazer-cat/walk.png", sit = "assets/generated/characters/green-blazer-cat/sit.png", use = "assets/generated/characters/green-blazer-cat/use.png" },
        ["blue-coaler-cat"] = { idle = "assets/generated/characters/blue-coaler-cat/idle.png", walk = "assets/generated/characters/blue-coaler-cat/walk.png", sit = "assets/generated/characters/blue-coaler-cat/sit.png" },
        ["business-dragon"] = { idle = "assets/generated/characters/business-dragon/idle.png", walk = "assets/generated/characters/business-dragon/walk.png", sit = "assets/generated/characters/business-dragon/sit.png" },
        ["business-fox"] = { idle = "assets/generated/characters/business-fox/idle.png", walk = "assets/generated/characters/business-fox/walk.png", sit = "assets/generated/characters/business-fox/sit.png" },
        ["business-cat"] = { idle = "assets/generated/characters/business-cat/idle.png", walk = "assets/generated/characters/business-cat/walk.png", sit = "assets/generated/characters/business-cat/sit.png" },
    },
}

return Config
