-- Explicit user-requested forklift-only resize. Other actors and pallet art
-- retain their established world scale.
local forkliftSizeMultiplier = 1.4
local Config = {
    baseWidth = 960,
    baseHeight = 678,
    businessCalendar = {
        secondsPerDay = 300,
        monthlyExpenses = { rent = 1200, power = 240, water = 85, internet = 125 },
    },
    player = {
        character = "rabbit-worker",
        spawnX = 500,
        spawnY = 455,
        speed = 155,
        drawScale = 0.30,
        acceleration = 1050,
        deceleration = 1350,
        maxFrameTime = 0.10,
        maxStepDistance = 5,
        walkPixelsPerFrame = 20,
        -- One value per gait pose: contact, weight-down, passing, knee-up,
        -- then the mirrored four-pose step. Both curves average to 1.0 so
        -- gait weight transfer does not change the player's overall pace.
        gaitSpeedMultipliers = { 0.96, 0.94, 1.04, 1.06, 0.96, 0.94, 1.04, 1.06 },
        gaitAccelerationMultipliers = { 0.92, 0.90, 1.08, 1.10, 0.92, 0.90, 1.08, 1.10 },
        idleAnimationRate = 0.65,
        interactionStickiness = 14,
        interactionFacingWeight = 18,
    },
    characterRendering = {
        -- Rabbit frames are 256px high. Normalized visitors use the same source
        -- height and world scale so every character reads at player size.
        referenceHeight = 256,
    },
    wallVentFan = {
        x = 118,
        y = 149,
        drawScale = 0.405,
        frameSize = 96,
        frameCount = 3,
        framesPerSecond = 7,
    },
    customer = {
        character = "business-dragon",
        characterPool = { "business-dragon", "business-fox", "business-cat" },
        drawScale = 0.30,
        speed = 72,
        walkAnimationRate = 4,
        idleAnimationRate = 0.65,
        useAnimationRate = 2.5,
        seatingPauseDuration = 0.28,
        motionProfiles = {
            ["business-cat"] = {
                walkPixelsPerFrame = 13,
                acceleration = 420,
                deceleration = 620,
                gaitSpeedMultipliers = { 0.96, 0.94, 1.04, 1.06, 0.96, 0.94, 1.04, 1.06 },
                gaitAccelerationMultipliers = { 0.92, 0.90, 1.08, 1.10, 0.92, 0.90, 1.08, 1.10 },
            },
        },
        -- The first customer demonstrates the reception loop quickly. Later
        -- clients arrive at varied business-day intervals instead of in a queue.
        initialArrivalDelayMin = 2,
        initialArrivalDelayMax = 6,
        arrivalDelayMin = 60,
        arrivalDelayMax = 150,
        maxWaitSeconds = 300,
        interactionRadius = 58,
        -- Main glass entrance to the client lounge.
        -- Every segment is kept inside the warehouse walk mask.
        route = {
            { x = 645, y = 235 },
            { x = 650, y = 245 },
            { x = 640, y = 270 },
            { x = 630, y = 295 },
            { x = 635, y = 320 },
            { x = 650, y = 340 },
            { x = 680, y = 350 },
            { x = 720, y = 355 },
            { x = 760, y = 360 },
        },
        seatSpots = {
            {
                name = "left-chair", x = 722, y = 296, facing = -1,
                approach = { { x = 744, y = 329 }, { x = 731, y = 312 } },
                foreground = "left-chair",
            },
            {
                name = "sofa-left", x = 782, y = 305, facing = -1,
                approach = { { x = 711, y = 337 }, { x = 731, y = 313 } },
                foreground = "coffee-table",
            },
            {
                name = "sofa-right", x = 827, y = 309, facing = 1,
                approach = { { x = 852, y = 346 }, { x = 850, y = 324 } },
                foreground = "coffee-table",
            },
            {
                name = "right-chair", x = 862, y = 349, facing = 1,
                approach = { { x = 873, y = 371 }, { x = 873, y = 357 } },
                foreground = "right-chair",
            },
        },
    },
    loungeSeating = {
        sourceWidth = 1536,
        sourceHeight = 1024,
        foregrounds = {
            ["left-chair"] = {
                asset = "loungeLeftChairForeground",
                sourceX = 1118, sourceY = 375, width = 96, height = 83,
            },
            ["coffee-table"] = {
                asset = "loungeCoffeeTableForeground",
                sourceX = 1200, sourceY = 410, width = 126, height = 91,
            },
            ["right-chair"] = {
                asset = "loungeRightChairForeground",
                sourceX = 1324, sourceY = 443, width = 119, height = 100,
            },
        },
    },
    vendor = {
        character = "tan-cat", drawScale = 0.30, speed = 68, walkAnimationRate = 4,
        useAnimationRate = 2.5,
        initialArrivalDelayMin = 15, initialArrivalDelayMax = 35,
        arrivalDelayMin = 120, arrivalDelayMax = 240,
        interactionRadius = 58,
        route = {
            { x = 645, y = 235 }, { x = 650, y = 245 }, { x = 640, y = 270 },
            { x = 630, y = 295 }, { x = 635, y = 320 }, { x = 650, y = 340 },
            { x = 680, y = 350 }, { x = 710, y = 340 },
        },
    },
    technician = {
        speed = 78,
        drawScale = 0.15,
        serviceDuration = 4,
        walkAnimationRate = 9,
        serviceAnimationRate = 5,
        route = {
            { x = 645, y = 235 }, { x = 650, y = 245 }, { x = 640, y = 270 },
            { x = 630, y = 295 }, { x = 635, y = 320 }, { x = 650, y = 340 },
        },
    },
    loadingBay = {
        sourceX = 200,
        sourceY = 170,
        frameWidth = 260,
        frameHeight = 260,
        frameCount = 5,
        duration = 0.9,
        interaction = { x = 300, y = 285, radius = 62 },
    },
    truck = {
        frameSize = 512,
        cargoFrameCount = 5,
        scheduleDelay = 1.25,
        backingDuration = 2.2,
        cargoDuration = 0.75,
        -- The truck keeps one physical size and follows the rear-facing axis
        -- painted into the isometric sprite. Its cab is on the left and its
        -- cargo opening is on the right, so backing must travel rightward with
        -- a slight downward pitch instead of sliding vertically across the
        -- truck's body.
        bodyAxis = { x = 1, y = 0.42 },
        start = { x = -150, y = 232, scale = 0.94 },
        -- The truck sprite's rear opening sits to the right of its image origin.
        -- This anchor places that opening on the loading-bay aperture center.
        -- At the parked scale the rear cargo opening fills the dock aperture
        -- (the truck body extends out onto the loading apron).
        parked = { x = 54, y = 318, scale = 0.94 },
        rearOpeningOffsetX = 160,
        interaction = { x = 218, y = 310, radius = 58 },
        obstacle = { offsetX = 0, offsetY = -8, radius = 72 },
        aperture = {
            { x = 138, y = 149 },
            { x = 270, y = 124 },
            { x = 270, y = 247 },
            { x = 138, y = 273 },
        },
    },
    cutterGui = {
        buttonFrameSize = 128,
        buttonFrameCount = 4,
        motionFrameWidth = 768,
        motionFrameHeight = 512,
        motionFrameCount = 5,
        maintenanceSpriteSize = 256,
        maintenanceSpriteCount = 4,
        maintenanceToolCell = 256,
        maintenanceSceneWidth = 512,
        maintenanceSceneHeight = 384,
    },
    cutterPlacement = {
        spawnX = 625,
        spawnY = 405,
        defaultDirection = "northwest",
        speed = 52,
        interactionRadius = 88,
        palletInputOffsetX = 78,
        palletInputOffsetY = 38,
        palletInputZoneRadius = 140,
        palletOutputOffsetX = 96,
        palletOutputOffsetY = 72,
        palletOutputSecondX = 164,
        palletOutputSecondY = 124,
        obstacleRadius = 68,
        collisionHalfWidth = 61,
        collisionHalfHeight = 19,
        operatorDistanceX = 82,
        operatorDistanceY = 48,
        drawScale = 0.272,
        frameSize = 512,
        frameCount = 8,
    },
    wrapperPlacement = {
        -- Factory-floor spawn, clear of the reception wall and lobby furniture.
        spawnX = 740,
        spawnY = 430,
        defaultDirection = "northwest",
        speed = 58,
        interactionRadius = 96,
        obstacleRadius = 44,
        collisionHalfWidth = 46,
        collisionHalfHeight = 17,
        operatorDistanceX = 54,
        operatorDistanceY = 34,
        palletRadius = 108,
        drawScale = 0.22,
        frameSize = 512,
        frameCount = 4,
    },
    windmillPlacement = {
        spawnX = 855,
        spawnY = 450,
        defaultDirection = "northwest",
        speed = 48,
        interactionRadius = 88,
        collisionHalfWidth = 50,
        collisionHalfHeight = 17,
        operatorDistanceX = 53,
        operatorDistanceY = 32,
        palletRadius = 120,
        drawScale = 0.196,
        frameWidth = 768,
        frameHeight = 512,
        frameCount = 4,
    },
    machineReceiving = {
        polar_115 = { x = 385, y = 350, direction = "northwest" },
        skid_wrapper = { x = 326, y = 338, direction = "northwest" },
        heidelberg_10x15 = { x = 300, y = 330, direction = "northwest" },
    },
    palletLogistics = {
        -- The loose-pallet art fills its frame while the pallet inside the
        -- loaded-jack composite occupies half a frame. This 0.5 ratio makes
        -- their visible world footprints match.
        drawScale = 0.26,
        obstacleRadius = 26,
        collisionHalfWidth = 33,
        collisionHalfHeight = 11,
        unloadDuration = 0.65,
        unloadOrigin = { x = 218, y = 304 },
        receivingLaneRadius = 34,
        interactionRadius = 86,
        spawnPoints = {
            { x = 338, y = 344 },
            { x = 410, y = 374 },
            { x = 482, y = 404 },
            { x = 360, y = 450 },
            { x = 442, y = 480 },
        },
    },
    warehouse = { enabled = true, provisionalArt = true, firstStorageOnly = false },
    forklift = {
        spawnX = 460, spawnY = 515, speed = 100, loadedSpeed = 72,
        liftDuration = 3, lowerDuration = 2.5, travelHeight = 0.08,
        maxStepDistance = 4, collisionHalfWidth = 34 * forkliftSizeMultiplier,
        collisionHalfHeight = 14 * forkliftSizeMultiplier,
        loadedCollisionHalfWidth = 42 * forkliftSizeMultiplier,
        loadedCollisionHalfHeight = 18 * forkliftSizeMultiplier,
        forkOffsetX = 46 * forkliftSizeMultiplier, forkOffsetY = 27 * forkliftSizeMultiplier,
        floorPickupRadius = 40, floorDropRadius = 24,
        drawScale = 0.22, parkedDrawScale = 0.25, visualScaleMultiplier = forkliftSizeMultiplier,
    },
    palletJack = {
        spawnX = 560,
        spawnY = 520,
        speed = 112,
        loadedSpeed = 82,
        interactionRadius = 58,
        pickupRadius = 68,
        obstacleRadius = 26,
        loadedObstacleRadius = 40,
        collisionHalfWidth = 34,
        collisionHalfHeight = 10,
        loadedCollisionHalfWidth = 44,
        loadedCollisionHalfHeight = 14,
        drawScale = 0.416,
        -- Keep carried pallet art at its established size while the jack itself
        -- is reduced by twenty percent.
        carriedPalletArtRatio = 0.625,
        operatorDistanceX = 42,
        operatorDistanceY = 24,
        frameSize = 256,
        frameCount = 8,
        palletFrameCount = 4,
    },
    placementGrid = {
        cellWidth = 32,
        cellHeight = 24,
        originX = 0,
        originY = 0,
        previewRadius = 3,
        selectionRadius = 104,
    },
    interactables = {
        computer = { x = 500, y = 185, radius = 62 },
        workPhone = {
            x = 399, y = 260, radius = 72,
            wallX = 399, wallY = 181, drawScale = 0.084,
        },
        cutter = { x = 625, y = 405, radius = 78 },
    },
    -- Only the taller upper architecture is registered in this slice. Existing
    -- floor/mask, furniture, live dock and all actor/equipment scales stay fixed.
    warehouseScene = { enabled = true },
    paths = {
        warehouse = "assets/generated/warehouse-layout-final.png",
        warehouseArchitecture = "assets/source/warehouse-expansion-v1/warehouse-base-v3-top-remake.png",
        walkmask = "assets/generated/warehouse-layout-final-walkmask.png",
        polar = "assets/generated/polar-115-sprite-sheet-clear-table-transparent.png",
        polarDirections = "assets/generated/polar-cutter-directions-strip.png",
        emptyPallet = "assets/generated/empty-pallet.png",
        paperStack = "assets/generated/paper-stack.png",
        toolboxSmall = "assets/generated/toolbox-small.png",
        toolboxLarge = "assets/generated/toolbox-large.png",
        paperBoxes = "assets/generated/paper-storage-boxes-strip.png",
        loadingBayDoor = "assets/generated/loading-bay-door-strip.png",
        deliveryTruck = "assets/generated/delivery-truck-open.png",
        truckCargoDoor = "assets/generated/truck-cargo-door-strip.png",
        machineFlatbedLoaded = "assets/generated/machine-delivery-flatbed-loaded.png",
        machineFlatbedEmpty = "assets/generated/machine-delivery-flatbed-empty.png",
        polarOperatorConsole = "assets/generated/polar-operator-console.png",
        cutterControlButtons = "assets/generated/cutter-control-buttons-strip.png",
        cutterClamp = "assets/generated/cutter-clamp-strip.png",
        cutterBlade = "assets/generated/cutter-blade-strip.png",
        cutterMaintenanceOil = "assets/generated/cutter-maintenance-oil-atlas.png",
        cutterMaintenanceTools = "assets/generated/cutter-maintenance-tools-atlas.png",
        cutterMaintenanceScenes = "assets/generated/cutter-maintenance-scenes-atlas.png",
        skidWrapperDirections = "assets/generated/skid-wrapper-directions-strip.png",
        wrapperMaintenanceAtlas = "assets/generated/skid-wrapper-maintenance-atlas.png",
        wrappedPalletStages = "assets/generated/wrapped-pallet-stages-strip.png",
        loadedPaperPallet = "assets/generated/loaded-paper-pallet.png",
        loadedPaperPalletDirections = "assets/generated/loaded-paper-pallet-directions-strip.png",
        palletJack = "assets/generated/pallet-jack-directions-strip.png",
        palletJackLoaded = "assets/generated/pallet-jack-loaded-directions-strip.png",
        wallVentFan = "assets/generated/wall-vent-fan-strip.png",
        loungeLeftChairForeground = "assets/generated/lounge/left-chair-foreground.png",
        loungeCoffeeTableForeground = "assets/generated/lounge/coffee-table-foreground.png",
        loungeRightChairForeground = "assets/generated/lounge/right-chair-foreground.png",
        vendorProductPallets = "assets/generated/vendor-product-pallets-atlas.png",
        boxedPaperPalletStages = "assets/generated/boxed-paper-pallet-stages-atlas.png",
        polarBackButton = "assets/generated/polar-back-button-states-strip.png",
        windmillDirections = "assets/generated/heidelberg-windmill-directions-atlas-v1.png",
        pressProcessStages = "assets/generated/press-process-stages-atlas-v3.png",
        pressOperatorHandbook = "assets/generated/heidelberg-operator-handbook-atlas-v2.png",
        pressSetupInteractions = "assets/generated/heidelberg-setup-interactions-atlas-v2.png",
        technicianNpcs = "assets/generated/technician-npcs-atlas-v1.png",
        palletWorkOrderPaper = "assets/generated/pallet-work-order-paper-v1.png",
        critterNetMenu = "assets/generated/critter-net-90s-menu-bg-v1.png",
        critterNetSprites = "assets/generated/critter-net-animated-icons-atlas-v1.png",
        workPhone = "assets/generated/critter-net-work-phone-atlas-v1.png",
        workOrderFont = "assets/fonts/SpecialElite-Regular.ttf",
        artwork = {
            ["ad-clothing"] = "assets/generated/artwork/ad-clothing.png",
            ["ad-critter-tattoo"] = "assets/generated/artwork/ad-critter-tattoo.png",
            ["ad-cut"] = "assets/generated/artwork/ad-cut.png",
            ["ad-delivery"] = "assets/generated/artwork/ad-delivery.png",
            ["ad-fashion-everyday-men"] = "assets/generated/artwork/ad-fashion-everyday-men.png",
            ["ad-fashion-everyday"] = "assets/generated/artwork/ad-fashion-everyday.png",
            ["ad-fashion-fox"] = "assets/generated/artwork/ad-fashion-fox.png",
            ["ad-fashion-outdoor-days"] = "assets/generated/artwork/ad-fashion-outdoor-days.png",
            ["ad-fashion-streetwear"] = "assets/generated/artwork/ad-fashion-streetwear.png",
            ["ad-fashion-tailored"] = "assets/generated/artwork/ad-fashion-tailored.png",
            ["ad-fashion-trail-gear"] = "assets/generated/artwork/ad-fashion-trail-gear.png",
            ["ad-fashion-utility-wear"] = "assets/generated/artwork/ad-fashion-utility-wear.png",
            ["ad-fashion-workwear"] = "assets/generated/artwork/ad-fashion-workwear.png",
            ["ad-garlic-bread"] = "assets/generated/artwork/ad-garlic-bread.png",
            ["ad-ink"] = "assets/generated/artwork/ad-ink.png",
            ["ad-kei-mini-delivery"] = "assets/generated/artwork/ad-kei-mini-delivery.png",
            ["ad-kei-mini-haul"] = "assets/generated/artwork/ad-kei-mini-haul.png",
            ["ad-kei-truck"] = "assets/generated/artwork/ad-kei-truck.png",
            ["ad-paper"] = "assets/generated/artwork/ad-paper.png",
            ["ad-photos"] = "assets/generated/artwork/ad-photos.png",
            ["ad-pizza"] = "assets/generated/artwork/ad-pizza.png",
            ["ad-safe"] = "assets/generated/artwork/ad-safe.png",
            ["ad-signs"] = "assets/generated/artwork/ad-signs.png",
            ["ad-swim-beach-club"] = "assets/generated/artwork/ad-swim-beach-club.png",
            ["ad-swim-pool-days"] = "assets/generated/artwork/ad-swim-pool-days.png",
            ["ad-swim-sun-surf"] = "assets/generated/artwork/ad-swim-sun-surf.png",
            ["ad-wrap"] = "assets/generated/artwork/ad-wrap.png",
            flower = "assets/generated/artwork/flower.png",
            cat = "assets/generated/artwork/cat.png",
            boat = "assets/generated/artwork/boat.png",
            landscape = "assets/generated/artwork/landscape.png",
            ["motorcycle-gsxr-600-action"] = "assets/generated/artwork/motorcycle-gsxr-600-action.png",
            ["motorcycle-gsxr-600-poster"] = "assets/generated/artwork/motorcycle-gsxr-600-poster.png",
            ["motorcycle-gsxr-600-side"] = "assets/generated/artwork/motorcycle-gsxr-600-side.png",
        },
    },
    artworkOrder = {
        "flower", "cat", "boat", "landscape", "ad-clothing", "ad-critter-tattoo",
        "ad-cut", "ad-delivery", "ad-fashion-everyday-men", "ad-fashion-everyday",
        "ad-fashion-fox", "ad-fashion-outdoor-days", "ad-fashion-streetwear",
        "ad-fashion-tailored", "ad-fashion-trail-gear", "ad-fashion-utility-wear",
        "ad-fashion-workwear", "ad-garlic-bread", "ad-ink", "ad-kei-mini-delivery",
        "ad-kei-mini-haul", "ad-kei-truck", "ad-paper", "ad-photos", "ad-pizza",
        "ad-safe", "ad-signs", "ad-swim-beach-club", "ad-swim-pool-days",
        "ad-swim-sun-surf", "ad-wrap", "motorcycle-gsxr-600-action",
        "motorcycle-gsxr-600-poster", "motorcycle-gsxr-600-side",
    },
    characters = {
        ["rabbit-worker"] = {
            idle = "assets/generated/characters/rabbit-worker/idle.png",
            idle_north = "assets/generated/characters/rabbit-worker/idle_north.png",
            idle_northeast = "assets/generated/characters/rabbit-worker/idle_northeast.png",
            idle_southeast = "assets/generated/characters/rabbit-worker/idle_southeast.png",
            idle_south = "assets/generated/characters/rabbit-worker/idle_south.png",
            walk = "assets/generated/characters/rabbit-worker/walk.png",
            walk_north = "assets/generated/characters/rabbit-worker/walk_north.png",
            walk_northeast = "assets/generated/characters/rabbit-worker/walk_northeast.png",
            walk_southeast = "assets/generated/characters/rabbit-worker/walk_southeast.png",
            walk_south = "assets/generated/characters/rabbit-worker/walk_south.png",
        },
        ["tan-cat"] = { idle = "assets/generated/characters/tan-cat/idle.png", walk = "assets/generated/characters/tan-cat/walk.png", sit = "assets/generated/characters/tan-cat/sit.png" },
        ["green-blazer-cat"] = { idle = "assets/generated/characters/green-blazer-cat/idle.png", walk = "assets/generated/characters/green-blazer-cat/walk.png", sit = "assets/generated/characters/green-blazer-cat/sit.png", use = "assets/generated/characters/green-blazer-cat/use.png" },
        ["blue-coaler-cat"] = { idle = "assets/generated/characters/blue-coaler-cat/idle.png", walk = "assets/generated/characters/blue-coaler-cat/walk.png", sit = "assets/generated/characters/blue-coaler-cat/sit.png" },
        ["business-dragon"] = { idle = "assets/generated/characters/business-dragon/idle.png", walk = "assets/generated/characters/business-dragon/walk.png", sit = "assets/generated/characters/business-dragon/sit.png" },
        ["business-fox"] = { idle = "assets/generated/characters/business-fox/idle.png", walk = "assets/generated/characters/business-fox/walk.png", sit = "assets/generated/characters/business-fox/sit.png" },
        ["business-cat"] = {
            idle = "assets/generated/characters/business-cat/idle.png",
            idle_north = "assets/generated/characters/business-cat/idle_north.png",
            idle_northeast = "assets/generated/characters/business-cat/idle_northeast.png",
            idle_southeast = "assets/generated/characters/business-cat/idle_southeast.png",
            idle_south = "assets/generated/characters/business-cat/idle_south.png",
            walk = "assets/generated/characters/business-cat/walk.png",
            walk_north = "assets/generated/characters/business-cat/walk_north.png",
            walk_northeast = "assets/generated/characters/business-cat/walk_northeast.png",
            walk_southeast = "assets/generated/characters/business-cat/walk_southeast.png",
            walk_south = "assets/generated/characters/business-cat/walk_south.png",
            sit = "assets/generated/characters/business-cat/sit.png",
        },
    },
}

return Config
