local StatusLabels = {}

local LABELS = {
    offered = "Offer",
    awaiting_delivery = "Awaiting inbound delivery",
    pending_arrival = "Waiting for promised delivery window",
    awaiting_schedule = "Awaiting truck schedule",
    scheduled = "Truck scheduled",
    arriving = "Truck en route",
    at_bay = "Truck at loading bay",
    cargo_open = "Cargo open",
    unloading = "Unloading",
    received = "Received",
    delivered = "Delivered",
    in_production = "In production",
    in_progress = "In production",
    cutting = "Cutting in progress",
    awaiting_cut = "Awaiting cutting",
    awaiting_print = "Awaiting printing",
    ready_to_print = "Ready to print",
    press_setup = "Press setup",
    setup = "Press setup",
    proof = "Proofing",
    proofing = "Proofing",
    approved = "Proof approved",
    production = "Printing in progress",
    printing = "Printing in progress",
    pass_complete = "Color pass complete",
    stock_shortage = "Client stock exhausted",
    drying = "Ink drying",
    printed = "Printed",
    complete = "Complete",
    ready_for_pickup = "Ready for pickup",
    pickup_in_progress = "Pickup in progress",
    loading = "Loading for pickup",
    loaded = "Loaded for pickup",
    departing = "Truck departing",
    completed = "Completed and paid",
    declined = "Declined",
    purchased = "Purchased",
    stocked = "Stocked",
    raw = "Raw paper",
    in_process = "In process",
    cut = "Cut",
    wrapped = "Wrapped",
    loaded_for_pickup = "Loaded for pickup",
    picked_up = "Picked up",
    cancelled = "Cancelled",
    warehouse = "Warehouse floor",
    on_pallet_jack = "On pallet jack",
    at_cutter = "At cutter",
    cutter_output = "Cutter output",
    at_press = "At press",
    press_output = "Press output",
    outbound_truck = "On pickup truck",
    truck = "On truck",
    none = "Not in shop",
}

function StatusLabels.get(status)
    return LABELS[status] or tostring(status or "Unknown")
end

return StatusLabels
